---
title: "ml_project_writeup.Rmd"
author: "Jason D. Miller"
date: "Sunday, December 21, 2014"
output:
  html_document:
    fig_caption: yes
---

# Practical Machine Learning Project Writeup

## Project Scope
This project uses data from the **Weight Lifting Exercise Dataset** to predict the manner in which exercisers wearing smartphone-powered biofeedback technology completed their exersies.

For details on the data please see `README.md` and `CodeBook.md`.

## R Scripts
The scripts I used in this project are:
1. functions.R -- which loads my libraries and custom functions
2. data.R -- which imports and cleans the data
3. run_analysis.R -- which builds and executes my machine learning algorithm

## Outcome
The outcome variable was `classe`, which categorizes the manner in which exercisers completed their exercises.

## Libraries and Functions
I called in a number of R packages (libraries), a subset of which was used in the final analysis, and defined 2 custom functions.

```
require(caret)
require(data.table)
require(MASS)
require(mlogit)
require(grid)
require(gtable)
require(rpart)
require(rattle)

ml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}


xyform <- function (y_var, x_vars) {
  # y_var: a length-one character vector
  # x_vars: a character vector of object names
  as.formula(sprintf("%s ~ %s", y_var, paste(x_vars, collapse = " + ")))
}
```

## Getting the Data
### Reading Data
The first step of this project was to import the test and training datasets from the Internet:

```
#download.file ("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv",
#               destfile = "train.csv")
#download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv",
#              destfile = "test.csv")

train <- read.csv("train.csv")
test  <- read.csv("test.csv")
```

### Cleaning the Data
The next step was to manipulate and massage the data into an analyst-friendly, tidy dataset.

This included removing columns of junk data, such as those which contained mostly NA's:

```
test$X       <- NULL
train$X      <- NULL
train.clean  <- train[,colSums(is.na(train)) < .5 * nrow(train)]
test.clean   <- test[,colSums(is.na(test)) < .5 * nrow(test)]
```

I saw no reason to keep columns in my training dataset that are not available in my prediction dataset, asides of course from the outcome variable:

```
train.clean0 <- train.clean[,colnames(train.clean) %in% colnames(test.clean)]

train.clean0$classe <- train.clean$classe
```

This allowed me to greatly reduce noise in the data -- meaning I only have to consider about 1/3 of the number of columns that I began with.

### Divide Labeled Data into Training and Testing
```
# 60-40 Split
inTrain       <- createDataPartition(train$classe, p=0.6, list=FALSE)
labeled.train <- train[inTrain,]
labeled.test  <- train[-inTrain,]
```

## Model Building
I tested a few different classification algorithms and packages during the model building phase.

Namely:

1. Multinomial logistic regression (via `mlogit`)  
2. Decision tree classification  (via `rpart`)  
3. Random Forest (via `randomForest`)  

```
# Using Multinomial Logistic Regression
long = mlogit.data(labeled.train,shape="wide",choice="classe")
logit.fit <- mlogit(classe ~ 0 | new_window + num_window + roll_belt + pitch_belt + 
                      yaw_belt + total_accel_belt + gyros_belt_x + gyros_belt_y + 
                      gyros_belt_z + accel_belt_x + accel_belt_y + accel_belt_z + 
                      magnet_belt_x + magnet_belt_y + magnet_belt_z + roll_arm + 
                      pitch_arm + yaw_arm + total_accel_arm + gyros_arm_x + gyros_arm_y + 
                      gyros_arm_z + accel_arm_x + accel_arm_y + accel_arm_z + magnet_arm_x + 
                      magnet_arm_y + magnet_arm_z + roll_dumbbell + pitch_dumbbell + 
                      yaw_dumbbell + total_accel_dumbbell + gyros_dumbbell_x + 
                      gyros_dumbbell_y + gyros_dumbbell_z + accel_dumbbell_x + 
                      accel_dumbbell_y + accel_dumbbell_z + magnet_dumbbell_x + 
                      magnet_dumbbell_y + magnet_dumbbell_z + roll_forearm + pitch_forearm + 
                      yaw_forearm + total_accel_forearm + gyros_forearm_x + gyros_forearm_y + 
                      gyros_forearm_z + accel_forearm_x + accel_forearm_y + accel_forearm_z + 
                      magnet_forearm_x , data=long) 

# Using rpart for Classification Desicision Trees
rpart.fit <- rpart(classe ~ ., data=labeled.train, method="class") 

# Using Random Forest 
rf.fit <- randomForest(classe ~ ., data=labeled.train)
```

## Cross Validation and Expected out of sample error 
My multinomial logit had a relatively high R-squared, but was less straightforward to compare with other algorithms due to lack of support for a  confusion matrix.

```
test.long  <- mlogit.data(labeled.test,shape="wide",choice="classe")
pred.logit <- predict(logit.fit, test.long)
summary(logit.fit)
```
```
> summary(logit.fit)

Call:
mlogit(formula = classe ~ 0 | new_window + num_window + roll_belt + 
    pitch_belt + yaw_belt + total_accel_belt + gyros_belt_x + 
    gyros_belt_y + gyros_belt_z + accel_belt_x + accel_belt_y + 
    accel_belt_z + magnet_belt_x + magnet_belt_y + magnet_belt_z + 
    roll_arm + pitch_arm + yaw_arm + total_accel_arm + gyros_arm_x + 
    gyros_arm_y + gyros_arm_z + accel_arm_x + accel_arm_y + accel_arm_z + 
    magnet_arm_x + magnet_arm_y + magnet_arm_z + roll_dumbbell + 
    pitch_dumbbell + yaw_dumbbell + total_accel_dumbbell + gyros_dumbbell_x + 
    gyros_dumbbell_y + gyros_dumbbell_z + accel_dumbbell_x + 
    accel_dumbbell_y + accel_dumbbell_z + magnet_dumbbell_x + 
    magnet_dumbbell_y + magnet_dumbbell_z + roll_forearm + pitch_forearm + 
    yaw_forearm + total_accel_forearm + gyros_forearm_x + gyros_forearm_y + 
    gyros_forearm_z + accel_forearm_x + accel_forearm_y + accel_forearm_z + 
    magnet_forearm_x, data = long, method = "nr", print.level = 0)

Frequencies of alternatives:
      A       B       C       D       E 
0.28431 0.19353 0.17442 0.16389 0.18385 

nr method
8 iterations, 0h:1m:38s 
g'(-H)^-1g = 8.54E-05 
successive function values within tolerance limits 

Coefficients :
                          Estimate  Std. Error  t-value  Pr(>|t|)    
B:(intercept)          27.47258061  6.11830564   4.4902 7.115e-06 ***
C:(intercept)          47.97563725  5.73852882   8.3603 < 2.2e-16 ***
D:(intercept)          71.67336715  5.49450656  13.0446 < 2.2e-16 ***
E:(intercept)          77.27502075  5.47221331  14.1213 < 2.2e-16 ***
B:new_windowyes         0.05057743  0.29306822   0.1726 0.8629823    
C:new_windowyes        -0.20329031  0.30114144  -0.6751 0.4996339    
D:new_windowyes        -0.03396304  0.30484061  -0.1114 0.9112893    
E:new_windowyes         0.12625346  0.31385479   0.4023 0.6874875    
B:num_window            0.00311745  0.00021973  14.1873 < 2.2e-16 ***
C:num_window            0.00221100  0.00021877  10.1065 < 2.2e-16 ***
D:num_window            0.00187351  0.00023398   8.0070 1.110e-15 ***
E:num_window           -0.00042843  0.00024899  -1.7207 0.0853102 .  
B:roll_belt             0.31370348  0.02036891  15.4011 < 2.2e-16 ***
C:roll_belt             0.26033022  0.02049953  12.6993 < 2.2e-16 ***
D:roll_belt             0.00557014  0.02064013   0.2699 0.7872609    
E:roll_belt             0.36469880  0.02050769  17.7835 < 2.2e-16 ***
B:pitch_belt           -0.56713716  0.03151669 -17.9948 < 2.2e-16 ***
C:pitch_belt           -0.34466150  0.02978255 -11.5726 < 2.2e-16 ***
D:pitch_belt           -0.35514647  0.03325697 -10.6789 < 2.2e-16 ***
E:pitch_belt           -0.21917476  0.02955321  -7.4163 1.203e-13 ***
B:yaw_belt             -0.22186965  0.01090247 -20.3504 < 2.2e-16 ***
C:yaw_belt             -0.21951285  0.01075377 -20.4126 < 2.2e-16 ***
D:yaw_belt             -0.18057447  0.01207103 -14.9593 < 2.2e-16 ***
E:yaw_belt             -0.19337717  0.01086352 -17.8006 < 2.2e-16 ***
B:total_accel_belt     -0.66524876  0.06488956 -10.2520 < 2.2e-16 ***
C:total_accel_belt     -0.34059164  0.06313897  -5.3943 6.878e-08 ***
D:total_accel_belt      0.17349570  0.06112380   2.8384 0.0045336 ** 
E:total_accel_belt     -0.03888891  0.06168250  -0.6305 0.5283877    
B:gyros_belt_x          0.03696262  0.57178146   0.0646 0.9484569    
C:gyros_belt_x          0.62962899  0.58416301   1.0778 0.2811092    
D:gyros_belt_x         -0.26276835  0.61177310  -0.4295 0.6675454    
E:gyros_belt_x          0.51786652  0.53217360   0.9731 0.3304958    
B:gyros_belt_y         -3.58335067  1.70916677  -2.0965 0.0360336 *  
C:gyros_belt_y         -0.46977537  1.61214524  -0.2914 0.7707472    
D:gyros_belt_y          0.03936529  1.55359377   0.0253 0.9797852    
E:gyros_belt_y         -4.12331114  1.45794744  -2.8282 0.0046816 ** 
B:gyros_belt_z          2.21372652  0.45119868   4.9063 9.280e-07 ***
C:gyros_belt_z          0.60883209  0.46523499   1.3087 0.1906512    
D:gyros_belt_z          0.52453601  0.41031468   1.2784 0.2011172    
E:gyros_belt_z          2.28156644  0.38985308   5.8524 4.846e-09 ***
B:accel_belt_x          0.02548333  0.01024988   2.4862 0.0129113 *  
C:accel_belt_x          0.00218849  0.00980641   0.2232 0.8234041    
D:accel_belt_x         -0.03405718  0.00991514  -3.4349 0.0005928 ***
E:accel_belt_x         -0.00817701  0.00932317  -0.8771 0.3804522    
B:accel_belt_y          0.05717163  0.01206561   4.7384 2.154e-06 ***
C:accel_belt_y          0.05398741  0.01138524   4.7419 2.117e-06 ***
D:accel_belt_y          0.01620373  0.01067608   1.5178 0.1290746    
E:accel_belt_y         -0.11133633  0.01050842 -10.5950 < 2.2e-16 ***
B:accel_belt_z         -0.00794258  0.00907822  -0.8749 0.3816257    
C:accel_belt_z         -0.03343768  0.00925838  -3.6116 0.0003043 ***
D:accel_belt_z         -0.09806424  0.00886544 -11.0614 < 2.2e-16 ***
E:accel_belt_z          0.00988606  0.00883189   1.1194 0.2629869    
B:magnet_belt_x        -0.06024363  0.00506139 -11.9026 < 2.2e-16 ***
C:magnet_belt_x        -0.01785224  0.00471003  -3.7903 0.0001505 ***
D:magnet_belt_x        -0.01714891  0.00482401  -3.5549 0.0003781 ***
E:magnet_belt_x        -0.00284933  0.00439987  -0.6476 0.5172475    
B:magnet_belt_y        -0.03407773  0.00823256  -4.1394 3.482e-05 ***
C:magnet_belt_y        -0.07242687  0.00769324  -9.4144 < 2.2e-16 ***
D:magnet_belt_y        -0.10222996  0.00726049 -14.0803 < 2.2e-16 ***
E:magnet_belt_y        -0.13144102  0.00725469 -18.1181 < 2.2e-16 ***
B:magnet_belt_z         0.05660690  0.00445078  12.7184 < 2.2e-16 ***
C:magnet_belt_z         0.08279096  0.00429690  19.2676 < 2.2e-16 ***
D:magnet_belt_z         0.07797485  0.00424891  18.3517 < 2.2e-16 ***
E:magnet_belt_z         0.07819432  0.00417068  18.7486 < 2.2e-16 ***
B:roll_arm              0.00556518  0.00094000   5.9204 3.211e-09 ***
C:roll_arm              0.00845972  0.00102081   8.2873 2.220e-16 ***
D:roll_arm             -0.00178683  0.00112731  -1.5850 0.1129581    
E:roll_arm              0.00337678  0.00114467   2.9500 0.0031777 ** 
B:pitch_arm             0.00260981  0.00200839   1.2995 0.1937885    
C:pitch_arm            -0.01159641  0.00205604  -5.6402 1.699e-08 ***
D:pitch_arm            -0.01990177  0.00219009  -9.0872 < 2.2e-16 ***
E:pitch_arm            -0.01225164  0.00254848  -4.8074 1.529e-06 ***
B:yaw_arm               0.00442316  0.00078662   5.6230 1.877e-08 ***
C:yaw_arm               0.00469385  0.00076707   6.1192 9.406e-10 ***
D:yaw_arm               0.00503377  0.00094196   5.3439 9.096e-08 ***
E:yaw_arm               0.00233131  0.00091565   2.5461 0.0108938 *  
B:total_accel_arm      -0.05125440  0.00640703  -7.9997 1.332e-15 ***
C:total_accel_arm      -0.02424491  0.00622301  -3.8960 9.779e-05 ***
D:total_accel_arm       0.07321103  0.00818160   8.9483 < 2.2e-16 ***
E:total_accel_arm       0.00732980  0.00677209   1.0824 0.2790955    
B:gyros_arm_x           0.09672204  0.07554558   1.2803 0.2004348    
C:gyros_arm_x           0.21075399  0.07769583   2.7126 0.0066767 ** 
D:gyros_arm_x           0.11083527  0.07870022   1.4083 0.1590357    
E:gyros_arm_x           0.26592030  0.07823787   3.3989 0.0006767 ***
B:gyros_arm_y          -0.12556709  0.18331313  -0.6850 0.4933522    
C:gyros_arm_y           0.24298135  0.19480513   1.2473 0.2122858    
D:gyros_arm_y          -0.07165340  0.21028901  -0.3407 0.7333010    
E:gyros_arm_y           0.09800253  0.19498822   0.5026 0.6152403    
B:gyros_arm_z          -0.24111603  0.13870773  -1.7383 0.0821575 .  
C:gyros_arm_z          -0.14258252  0.14368421  -0.9923 0.3210353    
D:gyros_arm_z          -0.24270140  0.15600949  -1.5557 0.1197834    
E:gyros_arm_z          -0.19965955  0.15054157  -1.3263 0.1847485    
B:accel_arm_x          -0.02457529  0.00159672 -15.3911 < 2.2e-16 ***
C:accel_arm_x          -0.01451579  0.00146048  -9.9391 < 2.2e-16 ***
D:accel_arm_x           0.00147037  0.00176563   0.8328 0.4049730    
E:accel_arm_x          -0.00931268  0.00157680  -5.9060 3.504e-09 ***
B:accel_arm_y          -0.00316286  0.00329450  -0.9600 0.3370337    
C:accel_arm_y          -0.01330227  0.00322630  -4.1231 3.739e-05 ***
D:accel_arm_y          -0.03006642  0.00368860  -8.1512 4.441e-16 ***
E:accel_arm_y           0.00189371  0.00346504   0.5465 0.5847084    
B:accel_arm_z           0.02643645  0.00193688  13.6490 < 2.2e-16 ***
C:accel_arm_z           0.02027494  0.00193162  10.4964 < 2.2e-16 ***
D:accel_arm_z           0.03245202  0.00204151  15.8961 < 2.2e-16 ***
E:accel_arm_z           0.03073072  0.00200079  15.3593 < 2.2e-16 ***
B:magnet_arm_x          0.00318800  0.00051246   6.2210 4.940e-10 ***
C:magnet_arm_x          0.00222357  0.00048124   4.6205 3.829e-06 ***
D:magnet_arm_x         -0.00148464  0.00059746  -2.4849 0.0129583 *  
E:magnet_arm_x         -0.00211285  0.00053132  -3.9766 6.991e-05 ***
B:magnet_arm_y          0.00502204  0.00136954   3.6670 0.0002455 ***
C:magnet_arm_y          0.00302710  0.00133835   2.2618 0.0237093 *  
D:magnet_arm_y          0.00044972  0.00152048   0.2958 0.7674022    
E:magnet_arm_y         -0.01208914  0.00147957  -8.1707 2.220e-16 ***
B:magnet_arm_z         -0.02146745  0.00085607 -25.0767 < 2.2e-16 ***
C:magnet_arm_z         -0.01083229  0.00080595 -13.4404 < 2.2e-16 ***
D:magnet_arm_z         -0.00661284  0.00089395  -7.3973 1.390e-13 ***
E:magnet_arm_z         -0.01156944  0.00085966 -13.4582 < 2.2e-16 ***
B:roll_dumbbell         0.00063219  0.00136186   0.4642 0.6424961    
C:roll_dumbbell         0.00362267  0.00143395   2.5264 0.0115251 *  
D:roll_dumbbell         0.01361358  0.00153795   8.8518 < 2.2e-16 ***
E:roll_dumbbell         0.00903902  0.00155210   5.8237 5.755e-09 ***
B:pitch_dumbbell       -0.01226100  0.00286685  -4.2768 1.896e-05 ***
C:pitch_dumbbell       -0.02184626  0.00310774  -7.0296 2.071e-12 ***
D:pitch_dumbbell       -0.00610500  0.00308685  -1.9777 0.0479575 *  
E:pitch_dumbbell       -0.01530284  0.00335882  -4.5560 5.213e-06 ***
B:yaw_dumbbell         -0.02132933  0.00145026 -14.7072 < 2.2e-16 ***
C:yaw_dumbbell         -0.02542989  0.00164661 -15.4438 < 2.2e-16 ***
D:yaw_dumbbell         -0.02214670  0.00159921 -13.8485 < 2.2e-16 ***
E:yaw_dumbbell         -0.02252997  0.00168286 -13.3879 < 2.2e-16 ***
B:total_accel_dumbbell  0.18961955  0.02014782   9.4114 < 2.2e-16 ***
C:total_accel_dumbbell  0.14237566  0.02112611   6.7393 1.591e-11 ***
D:total_accel_dumbbell -0.02807322  0.02543646  -1.1037 0.2697403    
E:total_accel_dumbbell  0.36243830  0.02130172  17.0145 < 2.2e-16 ***
B:gyros_dumbbell_x      0.38782117  0.18981891   2.0431 0.0410414 *  
C:gyros_dumbbell_x      1.48365635  0.20996359   7.0663 1.592e-12 ***
D:gyros_dumbbell_x      1.02532534  0.20627106   4.9708 6.669e-07 ***
E:gyros_dumbbell_x      0.45374852  0.20643876   2.1980 0.0279504 *  
B:gyros_dumbbell_y      0.12007806  0.13257218   0.9058 0.3650650    
C:gyros_dumbbell_y      1.37841947  0.14937541   9.2279 < 2.2e-16 ***
D:gyros_dumbbell_y      0.92073518  0.15476639   5.9492 2.695e-09 ***
E:gyros_dumbbell_y      0.47712760  0.14370039   3.3203 0.0008992 ***
B:gyros_dumbbell_z      0.31296905  0.18735461   1.6705 0.0948277 .  
C:gyros_dumbbell_z      0.76009295  0.19904477   3.8187 0.0001342 ***
D:gyros_dumbbell_z      0.47654148  0.22942149   2.0771 0.0377883 *  
E:gyros_dumbbell_z      0.56195612  0.20853381   2.6948 0.0070432 ** 
B:accel_dumbbell_x      0.03228134  0.00367544   8.7830 < 2.2e-16 ***
C:accel_dumbbell_x      0.05259991  0.00456359  11.5260 < 2.2e-16 ***
D:accel_dumbbell_x      0.01453050  0.00522279   2.7821 0.0054003 ** 
E:accel_dumbbell_x      0.05123547  0.00371853  13.7784 < 2.2e-16 ***
B:accel_dumbbell_y      0.01678715  0.00286692   5.8555 4.757e-09 ***
C:accel_dumbbell_y     -0.00106931  0.00305505  -0.3500 0.7263280    
D:accel_dumbbell_y      0.01624617  0.00344705   4.7131 2.440e-06 ***
E:accel_dumbbell_y      0.00752287  0.00297030   2.5327 0.0113189 *  
B:accel_dumbbell_z      0.01619681  0.00191187   8.4717 < 2.2e-16 ***
C:accel_dumbbell_z     -0.01413090  0.00279237  -5.0605 4.181e-07 ***
D:accel_dumbbell_z     -0.00931422  0.00307159  -3.0324 0.0024263 ** 
E:accel_dumbbell_z      0.01022902  0.00180053   5.6811 1.338e-08 ***
B:magnet_dumbbell_x    -0.00295556  0.00081639  -3.6203 0.0002943 ***
C:magnet_dumbbell_x    -0.01048091  0.00086157 -12.1649 < 2.2e-16 ***
D:magnet_dumbbell_x    -0.00773602  0.00092235  -8.3873 < 2.2e-16 ***
E:magnet_dumbbell_x    -0.01480100  0.00086942 -17.0240 < 2.2e-16 ***
B:magnet_dumbbell_y    -0.00853518  0.00066508 -12.8334 < 2.2e-16 ***
C:magnet_dumbbell_y    -0.01173218  0.00067480 -17.3863 < 2.2e-16 ***
D:magnet_dumbbell_y    -0.00732432  0.00071981 -10.1753 < 2.2e-16 ***
E:magnet_dumbbell_y    -0.00652061  0.00066546  -9.7987 < 2.2e-16 ***
B:magnet_dumbbell_z     0.01899418  0.00119958  15.8340 < 2.2e-16 ***
C:magnet_dumbbell_z     0.05361448  0.00152877  35.0704 < 2.2e-16 ***
D:magnet_dumbbell_z     0.04623581  0.00150401  30.7417 < 2.2e-16 ***
E:magnet_dumbbell_z     0.04223445  0.00141614  29.8235 < 2.2e-16 ***
B:roll_forearm          0.00364361  0.00057018   6.3903 1.655e-10 ***
C:roll_forearm          0.00517646  0.00057563   8.9927 < 2.2e-16 ***
D:roll_forearm          0.00340887  0.00056921   5.9887 2.115e-09 ***
E:roll_forearm          0.00623161  0.00060044  10.3783 < 2.2e-16 ***
B:pitch_forearm         0.02389870  0.00293593   8.1401 4.441e-16 ***
C:pitch_forearm         0.02775089  0.00313105   8.8631 < 2.2e-16 ***
D:pitch_forearm         0.05044601  0.00354729  14.2210 < 2.2e-16 ***
E:pitch_forearm         0.04313012  0.00347577  12.4088 < 2.2e-16 ***
B:yaw_forearm          -0.00189342  0.00062476  -3.0306 0.0024404 ** 
C:yaw_forearm          -0.00113790  0.00071947  -1.5816 0.1137474    
D:yaw_forearm          -0.00454403  0.00070602  -6.4361 1.226e-10 ***
E:yaw_forearm          -0.00243633  0.00069366  -3.5123 0.0004443 ***
B:total_accel_forearm   0.07600302  0.00733036  10.3683 < 2.2e-16 ***
C:total_accel_forearm   0.05964233  0.00806113   7.3988 1.374e-13 ***
D:total_accel_forearm   0.04688102  0.00866764   5.4087 6.347e-08 ***
E:total_accel_forearm   0.12580327  0.00823394  15.2786 < 2.2e-16 ***
B:gyros_forearm_x       0.07477915  0.12931289   0.5783 0.5630746    
C:gyros_forearm_x       0.19081222  0.13586451   1.4044 0.1601908    
D:gyros_forearm_x      -0.09450387  0.14952277  -0.6320 0.5273629    
E:gyros_forearm_x      -0.26959118  0.13493719  -1.9979 0.0457274 *  
B:gyros_forearm_y      -0.11761360  0.04288596  -2.7425 0.0060978 ** 
C:gyros_forearm_y       0.01809195  0.03974221   0.4552 0.6489418    
D:gyros_forearm_y      -0.03467021  0.04294040  -0.8074 0.4194343    
E:gyros_forearm_y      -0.16382303  0.04353418  -3.7631 0.0001678 ***
B:gyros_forearm_z       0.46566935  0.12392659   3.7576 0.0001715 ***
C:gyros_forearm_z       0.19313058  0.11392200   1.6953 0.0900208 .  
D:gyros_forearm_z       0.26844463  0.14031309   1.9132 0.0557246 .  
E:gyros_forearm_z       0.58837120  0.12923660   4.5527 5.297e-06 ***
B:accel_forearm_x       0.00597350  0.00098392   6.0711 1.270e-09 ***
C:accel_forearm_x       0.00425078  0.00100762   4.2187 2.458e-05 ***
D:accel_forearm_x      -0.00975085  0.00103411  -9.4292 < 2.2e-16 ***
E:accel_forearm_x       0.01142676  0.00101909  11.2127 < 2.2e-16 ***
B:accel_forearm_y      -0.00450980  0.00056488  -7.9837 1.332e-15 ***
C:accel_forearm_y      -0.00036086  0.00059088  -0.6107 0.5413850    
D:accel_forearm_y       0.00346665  0.00058605   5.9153 3.313e-09 ***
E:accel_forearm_y      -0.00556045  0.00057846  -9.6125 < 2.2e-16 ***
B:accel_forearm_z      -0.00151624  0.00095692  -1.5845 0.1130786    
C:accel_forearm_z      -0.01816496  0.00103477 -17.5546 < 2.2e-16 ***
D:accel_forearm_z      -0.01474075  0.00106762 -13.8071 < 2.2e-16 ***
E:accel_forearm_z      -0.02042375  0.00103219 -19.7868 < 2.2e-16 ***
B:magnet_forearm_x     -0.00257898  0.00038773  -6.6515 2.901e-11 ***
C:magnet_forearm_x     -0.00241265  0.00038799  -6.2184 5.023e-10 ***
D:magnet_forearm_x      0.00143077  0.00039241   3.6461 0.0002663 ***
E:magnet_forearm_x     -0.00453689  0.00039898 -11.3713 < 2.2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Log-Likelihood: -8093.7
McFadden R^2:  0.56713 
Likelihood ratio test : chisq = 21208 (p.value = < 2.22e-16)
```
```
summary(pred.logit)
```
```
       A                 B                  C                  D                  E           
 Min.   :0.00000   Min.   :0.000000   Min.   :0.000000   Min.   :0.000000   Min.   :0.000000  
 1st Qu.:0.00255   1st Qu.:0.008455   1st Qu.:0.005625   1st Qu.:0.002164   1st Qu.:0.008398  
 Median :0.04946   Median :0.053543   Median :0.044782   Median :0.028032   Median :0.042742  
 Mean   :0.28342   Mean   :0.193495   Mean   :0.173221   Mean   :0.166731   Mean   :0.183129  
 3rd Qu.:0.59709   3rd Qu.:0.267908   3rd Qu.:0.253856   3rd Qu.:0.192502   3rd Qu.:0.199767  
 Max.   :0.99998   Max.   :0.996681   Max.   :0.972115   Max.   :0.996424   Max.   :1.000000  
```

My decision tree predictor has accuracy of about 86.7% - 88.1% (95% CI):
```
pred.rpart <- predict(rpart.fit, labeled.test, type = "class")
confusionMatrix(pred.rpart, labeled.test$classe)
```
```
Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 2162   68    6    4    0
         B   56 1255   77   64    0
         C   14  187 1259  138   56
         D    0    8   14  873   77
         E    0    0   12  207 1309

Overall Statistics
                                          
               Accuracy : 0.8741          
                 95% CI : (0.8665, 0.8813)
    No Information Rate : 0.2845          
    P-Value [Acc > NIR] : < 2.2e-16       
                                          
                  Kappa : 0.8406          
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            0.9686   0.8267   0.9203   0.6788   0.9078
Specificity            0.9861   0.9689   0.9390   0.9849   0.9658
Pos Pred Value         0.9652   0.8643   0.7612   0.8981   0.8567
Neg Pred Value         0.9875   0.9589   0.9824   0.9399   0.9789
Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
Detection Rate         0.2756   0.1600   0.1605   0.1113   0.1668
Detection Prevalence   0.2855   0.1851   0.2108   0.1239   0.1947
Balanced Accuracy      0.9774   0.8978   0.9297   0.8319   0.9368
```

My final and best performing prediction algorithm was random forest, with 99.75 - 99.93% accuracy (95% CI)
```
pred.rf <- predict(rf.fit, labeled.test)
```
```
confusionMatrix(pred.rf, labeled.test$classe)
```
```
Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 2231    1    0    0    0
         B    1 1517    4    0    0
         C    0    0 1363    2    0
         D    0    0    1 1282    0
         E    0    0    0    2 1442

Overall Statistics
                                          
               Accuracy : 0.9986          
                 95% CI : (0.9975, 0.9993)
    No Information Rate : 0.2845          
    P-Value [Acc > NIR] : < 2.2e-16       
                                          
                  Kappa : 0.9982          
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            0.9996   0.9993   0.9963   0.9969   1.0000
Specificity            0.9998   0.9992   0.9997   0.9998   0.9997
Pos Pred Value         0.9996   0.9967   0.9985   0.9992   0.9986
Neg Pred Value         0.9998   0.9998   0.9992   0.9994   1.0000
Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
Detection Rate         0.2843   0.1933   0.1737   0.1634   0.1838
Detection Prevalence   0.2845   0.1940   0.1740   0.1635   0.1840
Balanced Accuracy      0.9997   0.9993   0.9980   0.9984   0.9998
```
## Visualization
```
fancyRpartPlot(rpart.fit)
plot(rf.fit)
```

## Prediction with Unlabeled Data
Finally, I predicted the (unlabeled) test data with my best model, which was the random forest:

```
result <- predict(rf.fit, test.clean, type = "class")
summary(result)
```